# Configuration file

# General settings
[General]
user = fjrodafo
port = 8080

# Database settings
[Database]
host = localhost
db_user = admin
db_password = pass

# Network settings
[Network]
ip = 192.168.1.1
port = 443
